import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from "sonner";
import React, { Suspense } from 'react';

import './globals.css';
import SheetProvider from "@/providers/sheet-provider";
import Providers from "@/providers/query-provider";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
       
         <Providers >
        <Toaster position="bottom-right" />
        <SheetProvider />        
        
        {children}
        </Providers>
       
      </body>
      </html>
    </ClerkProvider>
  );
}